export type Category =
  | "Trauma"
  | "Cardiac"
  | "Lung"
  | "OB/GYN"
  | "Abdominal"
  | "Vascular"
  | "Neuro"
  | "Thyroid"
  | "MSK"
  | "Procedural";

export interface Protocol {
  id: string;
  name: string;
  shortName: string;
  category: Category;
  indication: string;
  views: string[];
  keyFindings: string[];
  commonPitfalls: string[];
  tip: string;
  icon: string;
  difficulty: "Basic" | "Intermediate" | "Advanced";
  estimatedTime: string;
  aiMeasurements: string[];
  anomaliesDetected: string[];
  steps?: string[];
  measurements?: {
    structure: string;
    landmark: string;
    normal: string;
    technique?: string;
  }[];
}

export const PROTOCOLS: Protocol[] = [
  // ── TRAUMA ──────────────────────────────────────────────────────────────────
  {
    id: "efast",
    name: "eFAST — Extended FAST",
    shortName: "eFAST",
    category: "Trauma",
    indication: "Blunt/penetrating trauma; hemodynamic instability; free fluid assessment",
    views: ["RUQ (Morison's Pouch)", "LUQ (Splenorenal)", "Pelvis (Retrovesical/Retrouterine)", "Subxiphoid Cardiac", "Bilateral Lung (×2)"],
    keyFindings: ["Free fluid (anechoic stripe)", "Pericardial effusion", "Lung sliding (PTX)", "Hemopneumothorax"],
    commonPitfalls: ["Perinephric fat vs. fluid", "Collapsed IVC vs. fluid", "Suboptimal subxiphoid window"],
    tip: "Always start with RUQ — highest yield in trauma. Compare both flanks symmetrically.",
    icon: "🔴",
    difficulty: "Intermediate",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Free fluid depth (mm)", "Pericardial effusion size"],
    anomaliesDetected: ["Free fluid", "Pericardial effusion", "Pneumothorax", "Hemothorax"],
    steps: [
      "Position patient supine. Select phased array or curvilinear probe.",
      "Start at RUQ (Morison's pouch): place probe in right mid-axillary line, 8th–11th ICS, marker toward head. Look for anechoic fluid between liver and kidney.",
      "Move to LUQ (splenorenal): probe in left posterior axillary line, 8th–11th ICS. Look for fluid between spleen and left kidney and above the spleen.",
      "Pelvis: probe suprapubic, marker toward head (sagittal), then rotate 90° (transverse). Look for fluid posterior to bladder/uterus.",
      "Subxiphoid cardiac: flat probe angle under xiphoid, marker to patient's right. Look for pericardial effusion and gross cardiac function.",
      "Bilateral lung bases: probe at 2nd–3rd ICS, mid-clavicular line, marker toward head. Confirm lung sliding (rules out pneumothorax).",
      "Document each view. A positive eFAST (free fluid or absent sliding) warrants immediate surgical or clinical escalation.",
    ],
  },

  // ── CARDIAC ─────────────────────────────────────────────────────────────────
  {
    id: "tte",
    name: "Transthoracic Echocardiogram (TTE)",
    shortName: "TTE",
    category: "Cardiac",
    indication: "Dyspnea; chest pain; heart failure evaluation; valve disease; pre-op cardiac assessment",
    views: [
      "Parasternal Long Axis (PLAX)",
      "Parasternal Short Axis — MV level",
      "Parasternal Short Axis — Papillary level",
      "Apical 4-Chamber (A4C)",
      "Apical 5-Chamber (A5C)",
      "Apical 2-Chamber (A2C)",
      "Apical Long Axis (A3C/APLAX)",
      "Subcostal 4-Chamber",
      "Subcostal IVC",
      "Suprasternal Notch (aortic arch)",
    ],
    keyFindings: ["LV systolic function (EF)", "Wall motion abnormality", "Pericardial effusion", "Valve pathology (regurgitation/stenosis)", "RV size and function", "LA/RA size"],
    commonPitfalls: ["Foreshortened apical views overestimate EF", "Epicardial fat mistaken for pericardial effusion", "Lateral wall dropout in A4C", "Subcostal window limited by bowel gas"],
    tip: "Start with PLAX to align cardiac axis, then rotate to PSAX. Left lateral decubitus position improves apical window dramatically.",
    icon: "❤️",
    difficulty: "Advanced",
    estimatedTime: "45–60 min",
    aiMeasurements: ["LV EF (%)", "EPSS (mm)", "IVSd (mm)", "LVPWd (mm)", "LVIDd (mm)", "LA diameter (cm)", "Aortic root (cm)", "E/A ratio"],
    anomaliesDetected: ["Reduced EF (<55%)", "Wall motion abnormality", "Pericardial effusion", "Aortic stenosis", "Mitral regurgitation", "LV hypertrophy", "RV dilation"],
    steps: [
      "Position patient in left lateral decubitus. Select phased array probe.",
      "Begin with PLAX: probe at 3rd–4th ICS left sternal border, marker to patient's right shoulder. Align with cardiac long axis. Measure EPSS, LV dimensions, aortic root, LA.",
      "Rotate 90° clockwise to PSAX. Sweep from mitral valve (fish mouth) down to papillary level to apex. Assess for wall motion abnormalities and D-sign.",
      "Move to cardiac apex for A4C: probe at point of maximal impulse, marker toward left shoulder. Assess all four chambers, EF, MV and TV.",
      "Tilt anteriorly from A4C for A5C (LVOT/aortic valve). Rotate to A2C (marker down) then to APLAX.",
      "Subcostal window: patient supine, probe subxiphoid, marker to patient's left. Assess all chambers and measure IVC.",
      "Suprasternal notch: probe in suprasternal notch for aortic arch. Document all measurements per lab protocol.",
    ],
  },
  {
    id: "cardiac-plax",
    name: "Cardiac: Parasternal Long Axis",
    shortName: "PLAX",
    category: "Cardiac",
    indication: "Cardiac function assessment; effusion; valve pathology",
    views: ["Parasternal Long Axis (PLAX)"],
    keyFindings: ["LV systolic function", "Pericardial effusion", "Aortic root dilation", "MV pathology", "EPSS"],
    commonPitfalls: ["Mistaking epicardial fat for effusion", "Off-axis view overestimates chamber size"],
    tip: "Probe at 3rd–4th ICS, left sternal border. Rotate counterclockwise to align with cardiac axis.",
    icon: "❤️",
    difficulty: "Intermediate",
    estimatedTime: "2–3 min",
    aiMeasurements: ["EPSS (mm)", "LV internal dimension", "LA diameter", "Aortic root diameter"],
    anomaliesDetected: ["Pericardial effusion", "Reduced EF (EPSS >1cm)", "Aortic dilation", "Posterior effusion"],
    steps: [
      "Position patient supine or slight left lateral decubitus. Select phased array probe.",
      "Place probe at 3rd–4th ICS, left sternal border, marker pointing to right shoulder.",
      "Rotate probe until the cardiac long axis is aligned — LV, MV, aorta, and LA should all be in view.",
      "Optimize depth so the descending aorta is just visible at the bottom of the screen.",
      "Measure EPSS (E-point septal separation) in M-mode through the mitral valve — >1cm suggests reduced EF.",
      "Measure LV internal dimension, posterior wall, IVS, LA diameter, and aortic root in 2D or M-mode.",
      "Check posterior pericardial space for effusion. Note valve morphology and mobility.",
    ],
    measurements: [
      {
        structure: "LV End-Diastolic Diameter (LVEDD)",
        landmark: "M-mode or 2D at the level of the mitral valve leaflet tips, inner edge to inner edge, at end-diastole (largest LV dimension, onset of QRS).",
        normal: "3.9–5.3 cm (women); 4.2–5.9 cm (men); > 6.0 cm = dilated",
        technique: "Use M-mode through the PLAX view at the tip of the anterior mitral leaflet. Perpendicular to the long axis of the LV.",
      },
      {
        structure: "LV End-Systolic Diameter (LVESD)",
        landmark: "Same position as LVEDD, measured at end-systole (smallest LV dimension, peak of T-wave).",
        normal: "2.3–3.9 cm (women); 2.5–4.0 cm (men); > 4.0 cm = systolic dysfunction",
        technique: "Fractional shortening (FS) = (LVEDD − LVESD) / LVEDD × 100. Normal FS > 25%.",
      },
      {
        structure: "Interventricular Septum (IVS) Thickness",
        landmark: "Diastolic thickness of the IVS at the same M-mode position as LVEDD. Right side of septum to left side.",
        normal: "0.6–1.0 cm (women); 0.6–1.0 cm (men); > 1.2 cm = hypertrophy",
        technique: "Measure at end-diastole. Asymmetric hypertrophy (IVS/PW ratio > 1.3) suggests HCM.",
      },
      {
        structure: "Posterior Wall (PW) Thickness",
        landmark: "Diastolic thickness of the posterior LV wall, from the endocardial to epicardial surface.",
        normal: "0.6–1.0 cm; > 1.2 cm = hypertrophy",
        technique: "Measured at the same level as IVS (mitral valve tips). Increases with hypertension, HCM, amyloid.",
      },
      {
        structure: "Aortic Root / LVOT Diameter",
        landmark: "Aortic root: sinus of Valsalva to sinus of Valsalva at end-diastole, inner edge to inner edge.",
        normal: "Aortic root ≤ 3.7 cm (men) / ≤ 3.6 cm (women); LVOT ≈ 1.8–2.2 cm",
        technique: "Used to calculate stroke volume (SV = LVOT area × VTI from PSAX or A5C). Aortic root > 4.5 cm warrants referral.",
      },
      {
        structure: "Pericardial Effusion",
        landmark: "Largest echo-free space between pericardium and myocardium. Measure in diastole, in the view where effusion is largest.",
        normal: "< 0.5 cm = trivial; 0.5–1.0 cm = small; 1.0–2.0 cm = moderate; > 2.0 cm = large",
        technique: "PLAX is most sensitive. Confirm in PSAX and apical views. Circumferential vs. loculated. Tamponade: RV free wall collapse in diastole.",
      },
    ],
  },
  {
    id: "cardiac-psax",
    name: "Cardiac: Parasternal Short Axis",
    shortName: "PSAX",
    category: "Cardiac",
    indication: "Wall motion assessment; RV pressure; LV geometry",
    views: ["PSAX — Mitral valve level", "PSAX — Papillary muscle level", "PSAX — Apical level"],
    keyFindings: ["Regional wall motion abnormality", "D-sign (RV strain)", "LV geometry (donut shape)"],
    commonPitfalls: ["True short axis requires circular LV — if elliptical, adjust rotation"],
    tip: "From PLAX, rotate probe 90° clockwise. Mitral valve level shows 'fish mouth' appearance.",
    icon: "❤️",
    difficulty: "Intermediate",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Fractional shortening", "D-sign severity"],
    anomaliesDetected: ["Wall motion abnormality", "RV strain (D-sign)", "Pericardial effusion"],
    steps: [
      "From PLAX, rotate probe 90° clockwise (marker now pointing to left shoulder) to obtain PSAX.",
      "Sweep superiorly for aortic valve level (Mercedes-Benz sign), then inferiorly to mitral valve level (fish mouth).",
      "Continue to papillary muscle level — this is the standard level for wall motion assessment.",
      "The LV should appear as a perfect donut. If it looks elliptical, adjust probe rotation.",
      "Assess all 6 segments at papillary level for symmetric contraction.",
      "Look for D-sign: flattening of the interventricular septum in systole = RV pressure overload.",
      "Sweep to apical level — the LV should taper to a point with no papillary muscles visible.",
    ],
  },
  {
    id: "cardiac-a4c",
    name: "Cardiac: Apical 4-Chamber",
    shortName: "A4C",
    category: "Cardiac",
    indication: "EF estimation; chamber sizing; valve assessment",
    views: ["Apical 4-Chamber (A4C)"],
    keyFindings: ["All 4 chambers", "MV and TV function", "Apical wall motion", "EF (visual/biplane)"],
    commonPitfalls: ["Foreshortened apex gives falsely elevated EF", "Patient positioning critical (left lateral decubitus)"],
    tip: "Position patient in left lateral decubitus. Probe at cardiac apex, marker toward left shoulder.",
    icon: "❤️",
    difficulty: "Advanced",
    estimatedTime: "3–4 min",
    aiMeasurements: ["LV EF estimate (%)", "LA volume index", "E/A ratio estimate"],
    anomaliesDetected: ["Reduced EF", "RV dilation", "Apical wall motion abnormality", "Mitral regurgitation signs"],
    steps: [
      "Position patient in left lateral decubitus — this is essential for a non-foreshortened apex.",
      "Locate the cardiac apex by palpation or 2D guidance. Place probe at the point of maximal impulse.",
      "Orient marker toward the left shoulder. The LV should appear on the right of screen, RV on the left.",
      "Optimize until all four chambers are visible and the apex is at the top of the sector.",
      "Assess LV and RV size, wall motion in all visible segments, and gross EF visually.",
      "Evaluate mitral and tricuspid valves for regurgitation with color Doppler.",
      "Ensure the apex is not foreshortened — the LV should taper to a true point, not a flat wall.",
    ],
  },
  {
    id: "ivc",
    name: "IVC Collapsibility (Fluid Status)",
    shortName: "IVC",
    category: "Cardiac",
    indication: "Volume status assessment; fluid responsiveness; CVP estimation",
    views: ["Subxiphoid IVC (longitudinal)", "M-mode through IVC at 2cm from junction"],
    keyFindings: ["IVC diameter (max)", "Collapsibility with respiration", "Respiratory variation"],
    commonPitfalls: ["IVC vs. aorta confusion", "Spontaneous breathing vs. ventilated patients — opposite interpretation"],
    tip: "Measure IVC 2cm from IVC-RA junction. Collapsibility >50% = likely volume responsive (spontaneous breathing).",
    icon: "❤️",
    difficulty: "Basic",
    estimatedTime: "2 min",
    aiMeasurements: ["IVC max diameter (cm)", "IVC min diameter (cm)", "Collapsibility Index (%)"],
    anomaliesDetected: ["Dilated IVC (>2.1cm)", "Plethoric IVC", "Flat IVC (<0.9cm)"],
    steps: [
      "Position patient supine. Use phased array or curvilinear probe subxiphoid.",
      "Place probe at subxiphoid region, marker to patient's right, angled toward the right shoulder.",
      "Identify the IVC entering the right atrium in long axis — it runs to the right of the aorta.",
      "Slide probe slightly right and fan to obtain a clear longitudinal IVC view.",
      "Place M-mode cursor 2cm from the IVC–RA junction. Record diameter at max inspiration and expiration.",
      "For spontaneous breathers: collapsibility >50% = likely volume responsive. <50% = euvolemic or hypervolemic.",
      "For ventilated patients: distensibility index >18% with tidal volume challenge = volume responsive.",
    ],
  },

  // ── LUNG ─────────────────────────────────────────────────────────────────────
  {
    id: "lung-blue",
    name: "Lung: BLUE Protocol",
    shortName: "BLUE Protocol",
    category: "Lung",
    indication: "Dyspnea; respiratory failure; pneumonia vs. CHF vs. PE vs. PTX differentiation",
    views: ["Upper BLUE Point (bilateral)", "Lower BLUE Point (bilateral)", "PLAPS Point (bilateral)"],
    keyFindings: ["A-lines (air, normal/PTX)", "B-lines (fluid, interstitial)", "Lung sliding", "Pleural effusion", "Lung consolidation"],
    commonPitfalls: ["3+ B-lines per zone required to be significant", "Z-lines vs. B-lines (Z-lines don't reach far field)"],
    tip: "Use high-frequency linear probe for pleural line detail. Low-frequency for deeper pathology.",
    icon: "🫁",
    difficulty: "Intermediate",
    estimatedTime: "5–8 min",
    aiMeasurements: ["B-line count per zone", "Pleural effusion depth (mm)"],
    anomaliesDetected: ["B-lines (≥3/zone)", "Absent lung sliding", "Consolidation", "Pleural effusion"],
    steps: [
      "Select linear probe for pleural line detail or curvilinear for deeper pathology.",
      "Identify the Upper BLUE point (hand placed on chest, upper hand = upper zone) bilaterally.",
      "Assess Lower BLUE point (lower hand on chest) bilaterally. Note A-lines (horizontal, normal) vs. B-lines (vertical, comet-tail).",
      "≥3 B-lines per zone is significant. Bilateral B-lines = interstitial syndrome (CHF, pneumonia).",
      "Check for lung sliding at each point — absence = pneumothorax until proven otherwise.",
      "Assess PLAPS point (postero-lateral alveolar/pleural syndrome): probe in posterior axillary line above diaphragm. Look for effusion or consolidation.",
      "Integrate findings: A+A bilateral = normal/PE/asthma; B+B bilateral = CHF/pneumonia; A+B = pneumonia; C = consolidation.",
    ],
  },
  {
    id: "lung-effusion",
    name: "Lung: Pleural Effusion",
    shortName: "Pleural Effusion",
    category: "Lung",
    indication: "Pleural effusion detection and quantification; thoracentesis guidance",
    views: ["Posterior-lateral chest (sitting or lateral decubitus)", "Diaphragm visualization"],
    keyFindings: ["Anechoic vs. complex effusion", "Diaphragm descent", "Compressive atelectasis", "Fibrinous septations"],
    commonPitfalls: ["Confusing ascites with pleural effusion — find diaphragm landmark"],
    tip: "Spine sign: if vertebrae visible below diaphragm on left side, effusion present.",
    icon: "🫁",
    difficulty: "Basic",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Effusion depth (cm)", "Estimated volume (mL)"],
    anomaliesDetected: ["Simple effusion", "Complex/exudative effusion", "Septated effusion"],
    steps: [
      "Position patient sitting upright or in lateral decubitus. Select curvilinear probe.",
      "Place probe in the posterior-lateral chest, above the diaphragm, marker toward the head.",
      "Identify the diaphragm as the bright curved structure. Effusion appears as anechoic space above it.",
      "Use the spine sign on the left: if vertebral bodies are visible below the diaphragm, effusion is present.",
      "Characterize the effusion: simple (anechoic) vs. complex (echogenic debris, septations).",
      "Measure the maximal depth of the effusion. Estimate volume: depth (cm) × 90 ≈ volume (mL).",
      "Assess for lung compressive atelectasis (echogenic consolidated lung floating in fluid).",
    ],
  },

  // ── OB/GYN ───────────────────────────────────────────────────────────────────
  {
    id: "ob-first-trimester",
    name: "OB: First Trimester Dating",
    shortName: "OB 1st Tri",
    category: "OB/GYN",
    indication: "Gestational age confirmation; viable IUP; ectopic exclusion",
    views: ["Longitudinal uterus (GS)", "Embryo with CRL measurement", "Adnexa bilateral", "Cervix"],
    keyFindings: ["Gestational sac", "Yolk sac", "Embryo (CRL)", "Fetal cardiac motion", "Adnexal masses"],
    commonPitfalls: ["Pseudogestational sac (ectopic) vs. true GS — look for double decidual sign", "Empty sac — may be too early (<5.5 weeks)"],
    tip: "Transabdominal first, then transvaginal if unclear. CRL: straight line crown to rump, neutral position.",
    icon: "👶",
    difficulty: "Intermediate",
    estimatedTime: "5–10 min",
    aiMeasurements: ["CRL (mm)", "Gestational Age (weeks+days)", "EDD", "GS mean diameter (mm)"],
    anomaliesDetected: ["Subchorionic hematoma", "Irregular GS", "No cardiac motion (>6 weeks CRL)", "Adnexal mass", "Free fluid (ectopic risk)"],
    steps: [
      "Begin transabdominal with a full bladder (curvilinear probe). Survey uterus in sagittal and transverse planes.",
      "Identify gestational sac (GS) within the uterine cavity. Look for the double decidual sign to confirm IUP vs. pseudosac.",
      "Identify yolk sac (confirms IUP) and embryo. Activate M-mode over the embryo to confirm cardiac activity.",
      "Measure CRL: place calipers crown to rump in a neutral (not curled) position. This gives gestational age.",
      "Evaluate both adnexa for masses or free fluid — adnexal ring + free fluid raises ectopic concern.",
      "If transabdominal is inconclusive, proceed to transvaginal (empty bladder) for higher resolution.",
      "Document GS mean diameter (3-plane average), CRL, cardiac rate, and adnexal findings.",
    ],
  },
  {
    id: "ob-second-trimester",
    name: "OB: Second Trimester Biometry",
    shortName: "OB 2nd Tri",
    category: "OB/GYN",
    indication: "Gestational age; fetal growth; EFW; anatomy survey",
    views: ["BPD/HC plane (transthalamic)", "AC plane (stomach/UV junction)", "Femur length", "Placental location"],
    keyFindings: ["Fetal biometry parameters", "EFW percentile", "AFI/deepest pocket", "Placental position"],
    commonPitfalls: ["BPD: must visualize cavum septi pellucidi and thalami", "AC: true transverse at liver/umbilical vein junction"],
    tip: "Standard growth curves: Hadlock 1984 for EFW; Hadlock 1982 for individual parameters.",
    icon: "👶",
    difficulty: "Intermediate",
    estimatedTime: "10–15 min",
    aiMeasurements: ["BPD (mm)", "HC (mm)", "AC (mm)", "FL (mm)", "EFW (g)", "GA by biometry", "EFW percentile"],
    anomaliesDetected: ["IUGR pattern (AC lag)", "Macrosomia", "FL/AC discordance", "Placenta previa signs"],
    steps: [
      "Position patient supine with slight left tilt. Curvilinear probe, adequate gel.",
      "BPD/HC: axial plane through cavum septi pellucidi, thalami, and falx. No cerebellum visible. Measure outer-to-inner for BPD, outer perimeter for HC.",
      "AC: true transverse at the level of the stomach and umbilical vein junction (J-shaped). Measure outer perimeter.",
      "Femur length: visualize full femoral diaphysis, perpendicular to beam. Measure diaphysis only — not cartilaginous ends.",
      "Calculate EFW using Hadlock formula. Plot on growth chart and note percentile.",
      "Assess amniotic fluid: measure deepest vertical pocket (DVP) or AFI (four-quadrant sum).",
      "Document placental location relative to internal os. Note fetal presentation.",
    ],
  },
  {
    id: "pelvic-female",
    name: "Pelvic Ultrasound (Female)",
    shortName: "Pelvic US",
    category: "OB/GYN",
    indication: "Pelvic pain; abnormal uterine bleeding; ovarian cyst evaluation; infertility workup",
    views: [
      "Uterus — sagittal (length & AP)",
      "Uterus — transverse (width)",
      "Endometrium measurement",
      "Right ovary (longitudinal + transverse)",
      "Left ovary (longitudinal + transverse)",
      "Cul-de-sac (free fluid)",
      "Transvaginal survey (if indicated)",
    ],
    keyFindings: ["Uterine size and morphology", "Endometrial thickness", "Ovarian size and follicles", "Free fluid in cul-de-sac", "Adnexal masses"],
    commonPitfalls: ["Full bladder required for TA; empty bladder for TV", "Fibroids can distort uterine measurements", "Ovaries may be hidden behind bowel gas"],
    tip: "For postmenopausal bleeding: endometrial thickness >4–5mm warrants biopsy. Use TV for superior resolution of endometrium.",
    icon: "🔵",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Uterus length (cm)", "Uterus width (cm)", "Uterus AP (cm)", "Endometrial thickness (mm)", "Right ovary volume (cc)", "Left ovary volume (cc)"],
    anomaliesDetected: ["Endometrial thickening (>5mm postmenopausal)", "Ovarian cyst (simple/complex)", "Fibroid", "Free fluid", "Adnexal mass"],
    steps: [
      "Ensure patient has a full bladder for transabdominal (TA) scan. Use curvilinear probe.",
      "Sagittal uterus: probe suprapubic, marker toward head. Measure uterine length and AP diameter.",
      "Transverse uterus: rotate 90°, sweep superior to inferior. Measure width at widest point.",
      "Measure endometrial thickness in the sagittal plane — double layer, at the thickest point, excluding any fluid.",
      "Locate right ovary (lateral to uterus, medial to iliac vessels). Measure in 3 planes. Assess follicles.",
      "Locate left ovary similarly. Document any cysts — characterize as simple (anechoic, thin wall) or complex.",
      "Check cul-de-sac for free fluid. If TA is suboptimal, proceed to transvaginal (empty bladder) for endometrium and ovaries.",
    ],
  },
  {
    id: "scrotal",
    name: "Male Pelvis: Scrotal & Prostate",
    shortName: "Scrotal US",
    category: "OB/GYN",
    indication: "Scrotal pain; testicular mass; infertility evaluation; prostate assessment",
    views: [
      "Right testis — longitudinal",
      "Right testis — transverse (superior, mid, inferior)",
      "Left testis — longitudinal",
      "Left testis — transverse",
      "Bilateral epididymis (head, body, tail)",
      "Color/power Doppler — bilateral testes",
      "Transabdominal prostate (transverse + sagittal)",
    ],
    keyFindings: ["Testicular echogenicity and size", "Epididymis echogenicity", "Vascularity by Doppler", "Prostate size and echogenicity", "Intratesticular lesion"],
    commonPitfalls: ["Absent testicular flow on Doppler: torsion until proven otherwise — urgent urology referral", "Doppler settings must be optimized for low-flow states", "Compare both sides simultaneously with split-screen"],
    tip: "Split-screen color Doppler comparison is essential for torsion evaluation — side-by-side is the standard.",
    icon: "🔵",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Testis length, width, height (mm)", "Testicular volume (mL)", "Prostate volume (mL)", "Epididymal head diameter (mm)"],
    anomaliesDetected: ["Absent flow (torsion)", "Heterogeneous echotexture", "Intratesticular mass", "Epididymo-orchitis", "Hydrocele", "Varicocele", "Prostate enlargement"],
    steps: [
      "Position patient supine with a towel supporting the scrotum. Use high-frequency linear probe (10–18 MHz).",
      "Begin with the right testis in transverse: evaluate echogenicity, size, and any focal lesions. Measure length, width, height.",
      "Rotate to longitudinal for right testis — full sweep superior to inferior.",
      "Evaluate right epididymis (head at superior pole, body and tail posterolaterally). Note any enlargement or hyperemia.",
      "Apply color Doppler to right testis — document vascularity. Switch to split-screen to compare both sides simultaneously.",
      "Repeat all steps for left testis and epididymis. Any absent flow compared to contralateral = torsion until proven otherwise.",
      "Transabdominal prostate (full bladder): measure AP, transverse, and length. Calculate volume (0.523 × L × W × H).",
    ],
  },

  // ── ABDOMINAL ────────────────────────────────────────────────────────────────
  {
    id: "abdominal-complete",
    name: "Complete Abdominal Ultrasound",
    shortName: "Abdominal US",
    category: "Abdominal",
    indication: "Abdominal pain; abnormal LFTs; elevated creatinine; abdominal mass; general survey; pre-operative assessment",
    views: [
      "Liver — right lobe sagittal (hepatic veins)",
      "Liver — left lobe sagittal + transverse",
      "Gallbladder — long axis",
      "Gallbladder — short axis + Murphy's sign",
      "Common bile duct at porta hepatis",
      "Pancreas — transverse (head, body, tail)",
      "Spleen — long axis (craniocaudal length)",
      "Right kidney — long axis + transverse",
      "Left kidney — long axis + transverse",
      "Aorta — transverse (at celiac, SMA, bifurcation)",
      "IVC — longitudinal",
      "Bladder — transverse + sagittal (post-void if indicated)",
    ],
    keyFindings: [
      "Liver echogenicity, size, and surface contour",
      "Gallstones (hyperechoic + posterior shadowing + mobility)",
      "GB wall thickness and pericholecystic fluid",
      "CBD diameter",
      "Pancreatic duct dilation or masses",
      "Spleen size and echogenicity",
      "Kidney size, cortical thickness, hydronephrosis",
      "Aortic diameter (rule out AAA)",
      "Free fluid / ascites in all quadrants",
    ],
    commonPitfalls: [
      "Patient must fast ≥4h for GB assessment — contracted GB misses stones",
      "Bowel gas commonly obscures pancreas — scan in various positions or use water as acoustic window",
      "Always measure the aorta in TRANSVERSE — sagittal view underestimates diameter",
      "Kidney echogenicity is relative — compare to liver (right) and spleen (left)",
      "Absent or collapsed IVC suggests hypovolemia",
    ],
    tip: "Start with the gallbladder in the right lateral decubitus position for best distension. Scan the aorta last — patient will often have passed more gas by then.",
    icon: "🫁",
    difficulty: "Intermediate",
    estimatedTime: "45–60 min",
    aiMeasurements: [
      "Liver span (cm)", "GB wall thickness (mm)", "CBD diameter (mm)",
      "Pancreatic duct diameter (mm)", "Spleen length (cm)",
      "Right kidney length (cm)", "Left kidney length (cm)",
      "Aortic diameter (cm)", "Bladder volume (mL)",
    ],
    anomaliesDetected: [
      "Cholelithiasis / cholecystitis", "CBD dilation", "Hepatomegaly / steatosis / cirrhosis",
      "Splenomegaly", "Hydronephrosis / renal calculi", "AAA (aorta >3 cm)",
      "Ascites", "Pancreatic duct dilation", "Bladder wall thickening",
    ],
    steps: [
      "Patient fasting ≥4h. Position supine. Use curvilinear probe (3.5–5 MHz). Begin with gallbladder.",
      "Gallbladder: intercostal oblique view (right mid-axillary line). Scan in long and short axis. Roll patient left to confirm stone mobility. Apply direct probe pressure for sonographic Murphy's sign.",
      "Measure GB wall (anterior, inner-to-outer) and CBD (inner-to-inner, at porta hepatis anterior to portal vein).",
      "Liver: sagittal sweep right to left — assess echogenicity (compare to right kidney cortex), surface contour, size. Measure craniocaudal span at mid-clavicular line.",
      "Identify hepatic veins draining to IVC, and portal vein at porta hepatis. Note any dilation, thrombosis, or mass.",
      "Pancreas: transverse view at epigastrium, angling inferiorly. Use the splenic vein as a posterior landmark. Survey head (anterior to IVC), body (anterior to aorta), and tail (anterior to left kidney). Note echogenicity and duct size.",
      "Spleen: left lateral decubitus or right posterior oblique. Measure maximum craniocaudal length in long axis. Assess echogenicity and parenchymal texture.",
      "Right kidney: right flank, coronal view. Measure length in long axis. Assess cortical echogenicity, cortical thickness, central sinus, and collecting system. Grade any hydronephrosis.",
      "Left kidney: left flank or posterior approach. Same assessment as right — compare cortical echogenicity to spleen.",
      "Aorta: midline transverse at epigastrium. Follow aorta from diaphragm (celiac axis) to bifurcation. Measure outer-to-outer diameter at widest point. Document in TRANSVERSE only.",
      "IVC: longitudinal, right of midline. Assess diameter and respiratory variation (collapsed on inspiration = hypovolemia).",
      "Bladder: suprapubic transverse and sagittal. Measure three dimensions if post-void volume needed. Note wall thickness and intraluminal contents.",
    ],
    measurements: [
      {
        structure: "Liver Span",
        landmark: "Right mid-clavicular line, sagittal view. Place calipers at the dome of the right lobe to the inferior tip.",
        normal: "≤ 15 cm (mid-clavicular line); > 17 cm = hepatomegaly",
        technique: "Obtain with patient in inspiration. Ensure the full craniocaudal extent is visible before measuring.",
      },
      {
        structure: "Gallbladder Wall Thickness",
        landmark: "Anterior GB wall only, in long axis. Outer wall margin to inner wall margin (where GB lumen begins).",
        normal: "< 3 mm (fasting); wall ≥ 3 mm + Murphy's + stones = acute cholecystitis",
        technique: "Measure the ANTERIOR wall only — posterior wall is artifactually thickened by acoustic enhancement from GB bile.",
      },
      {
        structure: "Common Bile Duct (CBD)",
        landmark: "At the porta hepatis, anterior to the portal vein, inner wall to inner wall. Use the widest visible lumen.",
        normal: "≤ 6 mm; ≤ 7–8 mm post-cholecystectomy; add ~1 mm per decade after age 60",
        technique: "Do not include wall. Scan in intercostal oblique or subcostal approach. If dilated, follow duct distally to identify obstruction level.",
      },
      {
        structure: "Spleen Length",
        landmark: "Maximum craniocaudal length in the long axis, coronal view. Dome to inferior tip.",
        normal: "≤ 12 cm (adults); > 13 cm = splenomegaly",
        technique: "Left lateral decubitus position improves visualization. Place probe in left posterior axillary line.",
      },
      {
        structure: "Kidney Length",
        landmark: "Long axis, maximum pole-to-pole length. Include full extent of renal parenchyma from upper to lower pole.",
        normal: "9–12 cm (adults); < 8 cm suggests chronic renal disease; asymmetry > 1.5 cm is significant",
        technique: "Measure in a single sweep from upper to lower pole. Compare both sides. Cortical thickness: normal ≥ 1 cm.",
      },
      {
        structure: "Abdominal Aortic Diameter",
        landmark: "Widest transverse diameter, outer wall to outer wall. Measure at the level of maximum dilation.",
        normal: "< 3 cm; 3–5.4 cm = AAA (monitor); ≥ 5.5 cm = surgical threshold in most guidelines",
        technique: "Always measure in TRANSVERSE — sagittal views underestimate diameter. Measure at celiac axis, SMA, and just above bifurcation.",
      },
      {
        structure: "Pancreatic Duct",
        landmark: "Body of pancreas, transverse view. Lumen of the main pancreatic duct, inner wall to inner wall.",
        normal: "≤ 2 mm (body); ≤ 3 mm acceptable; > 3 mm = dilation (worry: chronic pancreatitis, pancreatic mass)",
        technique: "Use the splenic vein as a landmark just posterior to the pancreas body. Fan the probe slightly inferior to see the duct.",
      },
      {
        structure: "Bladder Volume (Post-Void Residual)",
        landmark: "Three orthogonal dimensions: transverse width (W), anteroposterior depth (AP), and craniocaudal height (H) — all in cm.",
        normal: "Post-void residual < 50 mL normal; 50–100 mL borderline; > 100 mL = incomplete emptying",
        technique: "Formula: Volume (mL) = 0.52 × W × AP × H. Measure immediately after voiding for PVR.",
      },
    ],
  },
  {
    id: "ruq",
    name: "Right Upper Quadrant (RUQ) Ultrasound",
    shortName: "RUQ US",
    category: "Abdominal",
    indication: "RUQ pain; abnormal LFTs; jaundice; gallstones; hepatomegaly evaluation",
    views: [
      "Liver — longitudinal (right lobe)",
      "Liver — transverse (portal vein + hepatic veins)",
      "Gallbladder — long axis",
      "Gallbladder — short axis",
      "CBD measurement at porta hepatis",
      "Murphy's sign assessment",
      "Right kidney — longitudinal (comparison)",
    ],
    keyFindings: ["Gallstones (hyperechoic + posterior shadowing)", "GB wall thickness", "CBD diameter", "Liver echogenicity and size", "Sonographic Murphy's sign", "Pericholecystic fluid"],
    commonPitfalls: ["Fasting ≥4h required — contracted GB obscures stones", "WES (wall-echo-shadow) sign = packed stones; can be mistaken for gas", "CBD measured inner wall to inner wall at porta hepatis"],
    tip: "Start in right intercostal oblique, sweep through GB. Roll patient left to confirm stone mobility. CBD >6mm (or >7mm post-cholecystectomy) is abnormal.",
    icon: "🟡",
    difficulty: "Basic",
    estimatedTime: "30–45 min",
    aiMeasurements: ["GB wall thickness (mm)", "CBD diameter (mm)", "Stone size (mm)", "Liver span (cm)"],
    anomaliesDetected: ["Cholelithiasis", "Acute cholecystitis (wall >3mm + Murphy's + stones)", "CBD dilation (>6mm)", "Hepatomegaly", "Hepatic steatosis", "Pericholecystic fluid"],
    steps: [
      "Patient should be fasting ≥4 hours for optimal GB distension. Use curvilinear probe.",
      "Begin with liver in sagittal: sweep from right lobe to left lobe, assessing echogenicity, size, and parenchymal texture.",
      "Locate gallbladder in intercostal oblique view (right mid-axillary line). Survey in long and short axis.",
      "Roll patient to left decubitus to confirm stone mobility and assess for pericholecystic fluid.",
      "Measure GB wall thickness at the anterior wall (normal <3mm). Apply direct probe pressure for sonographic Murphy's sign.",
      "Locate CBD at the porta hepatis (anterior to portal vein). Measure inner-to-inner diameter (normal ≤6mm).",
      "Scan right kidney longitudinally as comparison for echogenicity assessment vs. liver.",
    ],
    measurements: [
      {
        structure: "Gallbladder Wall Thickness",
        landmark: "Anterior GB wall, perpendicular to the wall, in long-axis view. Place calipers at the outer to inner wall margin.",
        normal: "< 3 mm (fasting state)",
        technique: "Measure the anterior wall only — posterior wall measurement is artifactually thickened by acoustic enhancement.",
      },
      {
        structure: "Common Bile Duct (CBD)",
        landmark: "At the porta hepatis, anterior to the portal vein, in the long axis. Measure inner wall to inner wall.",
        normal: "≤ 6 mm (≤ 7–8 mm post-cholecystectomy; add 1 mm per decade over 60)",
        technique: "Do not include the wall itself. Use the widest visible lumen diameter in the oblique subcostal or intercostal view.",
      },
      {
        structure: "Liver Span",
        landmark: "Right lobe in the right mid-clavicular line, sagittal view. Measure craniocaudal length from dome to inferior tip.",
        normal: "≤ 15 cm (mid-clavicular line)",
        technique: "Include the full craniocaudal extent. A liver >17 cm is strongly suggestive of hepatomegaly.",
      },
      {
        structure: "Gallstone Size",
        landmark: "Measure the largest stone in two perpendicular planes. Place calipers at the leading edges of the hyperechoic focus.",
        normal: "N/A — any stone is abnormal",
        technique: "Confirm mobility by rolling the patient. Stones >1 cm carry higher risk of complications.",
      },
    ],
  },
  {
    id: "gallbladder",
    name: "Gallbladder",
    shortName: "Gallbladder",
    category: "Abdominal",
    indication: "RUQ pain; suspected cholecystitis; biliary colic; jaundice",
    views: ["Long-axis GB", "Short-axis GB", "CBD measurement", "Murphy's sign assessment"],
    keyFindings: ["Stones (hyperechoic + shadowing)", "Wall thickness (>3mm)", "Pericholecystic fluid", "CBD diameter", "Sonographic Murphy's sign"],
    commonPitfalls: ["Fasting state required ideally", "Contracted GB makes assessment difficult", "Polyps vs. stones (stones move with gravity)"],
    tip: "Stones move with patient position (roll patient). Wall-echo-shadow (WES) sign = packed stones.",
    icon: "🟡",
    difficulty: "Basic",
    estimatedTime: "3–5 min",
    aiMeasurements: ["GB wall thickness (mm)", "CBD diameter (mm)", "Stone size (mm)"],
    anomaliesDetected: ["Cholelithiasis", "Wall thickening >3mm", "Pericholecystic fluid", "CBD dilation >6mm", "Polyp"],
    steps: [
      "Patient fasting ≥4 hours ideally. Use curvilinear probe, right intercostal oblique approach.",
      "Identify GB in long axis: look for the pear-shaped fluid-filled structure under the right lobe of the liver.",
      "Rotate to short axis. Evaluate wall thickness at the anterior wall — measure at the near wall.",
      "Look for stones: hyperechoic foci with posterior acoustic shadowing. Small stones may not shadow.",
      "Roll patient left — confirm mobile echogenic foci = stones (fixed = polyps or sludge).",
      "Apply direct probe pressure over the GB while patient holds breath — positive Murphy's sign = focal tenderness.",
      "Measure CBD at the porta hepatis, anterior to the portal vein. Inner-to-inner >6mm is abnormal.",
    ],
  },
  {
    id: "renal",
    name: "Renal (Hydronephrosis)",
    shortName: "Renal",
    category: "Abdominal",
    indication: "Flank pain; UTI; renal colic; acute kidney injury",
    views: ["Right kidney (longitudinal + transverse)", "Left kidney (longitudinal + transverse)", "Bladder (transverse + sagittal)"],
    keyFindings: ["Hydronephrosis grade", "Kidney size", "Cortical thickness", "Stones", "Perinephric fluid"],
    commonPitfalls: ["Renal sinus fat vs. hydronephrosis", "Full bladder causes false hydronephrosis — rescan post-void"],
    tip: "Grade: Mild = renal pelvis only; Moderate = calyces; Severe = cortical thinning.",
    icon: "🟤",
    difficulty: "Basic",
    estimatedTime: "4–6 min",
    aiMeasurements: ["Kidney length (cm)", "Cortical thickness (mm)", "Hydronephrosis grade"],
    anomaliesDetected: ["Hydronephrosis (mild/mod/severe)", "Renal stone", "Perinephric collection", "Cortical thinning"],
    steps: [
      "Position patient supine or slightly oblique. Use curvilinear probe.",
      "Right kidney: probe in right mid-axillary line, 9th–11th ICS, marker toward head. Use liver as acoustic window.",
      "Left kidney: probe in left posterior axillary line. Ask patient to take a deep breath to bring kidney into view.",
      "Scan each kidney in full longitudinal sweep, then rotate to transverse. Measure length (longitudinal), width, and AP.",
      "Assess renal pelvis and calyces: anechoic separation = hydronephrosis. Grade mild (pelvis only), moderate (calyces), severe (cortical thinning).",
      "Look for stones: hyperechoic foci with posterior shadowing, often at the UPJ or ureter.",
      "Scan bladder transverse and sagittal: assess for distal ureteral jets with color Doppler and post-void residual.",
    ],
  },
  {
    id: "bladder-volume",
    name: "Bladder Volume",
    shortName: "Bladder Vol",
    category: "Abdominal",
    indication: "Urinary retention; post-void residual; catheter need assessment",
    views: ["Transverse bladder (max width + depth)", "Sagittal bladder (max length)"],
    keyFindings: ["3D dimensions for ellipsoid formula", "Wall abnormalities", "Intraluminal pathology"],
    commonPitfalls: ["Ovarian cysts can mimic bladder — trace the bladder wall continuously"],
    tip: "Volume = 0.523 × L × W × H. >300mL suggests urinary retention.",
    icon: "🔵",
    difficulty: "Basic",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Bladder length (cm)", "Width (cm)", "Height (cm)", "Volume (mL)"],
    anomaliesDetected: ["Retention (>300mL)", "Debris/clot", "Mass", "Thickened wall"],
    steps: [
      "Patient should not have voided recently. Use curvilinear probe suprapubically.",
      "Transverse plane: place probe just above the pubic symphysis, marker to patient's right. Measure width (W) and AP depth (D) at the widest point.",
      "Rotate 90° to sagittal plane. Measure the longest craniocaudal dimension (L).",
      "Calculate volume: 0.523 × L × W × D. Values >300mL suggest urinary retention.",
      "Trace the bladder wall continuously in both planes to confirm it is bladder (not an ovarian cyst).",
      "Assess for wall thickening (>3mm when full = abnormal), intraluminal debris, or masses.",
      "If post-void residual needed: scan immediately after voiding. PVR >100mL is significant.",
    ],
    measurements: [
      {
        structure: "Bladder Volume / Post-Void Residual",
        landmark: "Three orthogonal dimensions measured at maximum bladder dimensions: transverse width (W) in the transverse plane, anteroposterior depth (AP) in the transverse plane, and craniocaudal height (H) in the sagittal plane.",
        normal: "Pre-void: volume >300 mL suggests retention. Post-void residual: < 50 mL = normal; 50–100 mL = borderline; > 100 mL = incomplete emptying",
        technique: "Formula: Volume (mL) = 0.523 × W × AP × H. Scan immediately after voiding for accurate PVR. Trace the bladder wall continuously to confirm it is the bladder (not an adnexal cyst).",
      },
      {
        structure: "Bladder Wall Thickness",
        landmark: "Anterolateral wall measured in the transverse plane, at a site free of trabeculation, when the bladder is adequately filled.",
        normal: "≤ 3 mm (when bladder is full/adequately distended); > 3 mm with full bladder = wall thickening",
        technique: "Wall thickness is dependent on distension — always note the estimated bladder volume at the time of measurement. A poorly filled bladder will appear falsely thick.",
      },
    ],
  },

  // ── VASCULAR ─────────────────────────────────────────────────────────────────
  {
    id: "carotid-duplex",
    name: "Carotid Duplex Ultrasound",
    shortName: "Carotid Duplex",
    category: "Vascular",
    indication: "TIA/stroke workup; carotid bruit; pre-operative assessment; stenosis surveillance",
    views: [
      "CCA — transverse sweep (proximal to bifurcation)",
      "CCA — sagittal + Doppler (proximal, mid, distal)",
      "Bifurcation — grayscale + Doppler",
      "ICA — sagittal + Doppler (proximal, mid, distal)",
      "ECA — sagittal + Doppler",
      "Vertebral artery — sagittal + Doppler (bilateral)",
      "Repeat contralateral side",
    ],
    keyFindings: ["Intimal-medial thickness (IMT)", "Plaque (location, echogenicity, surface)", "PSV/EDV at CCA, ICA, ECA", "ICA/CCA PSV ratio", "Vertebral flow direction"],
    commonPitfalls: ["Doppler angle must not exceed 60° — perpendicular angles are contraindicated", "Distinguish physiologic bifurcation turbulence from pathologic stenosis", "Retrograde vertebral flow = subclavian steal syndrome"],
    tip: "Temporal artery tap test: brief tapping on the superficial temporal artery creates a 'bouncing' waveform in the ECA — confirms ICA vs. ECA identity.",
    icon: "🩸",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["IMT (mm)", "CCA PSV (cm/s)", "ICA PSV (cm/s)", "ICA/CCA ratio", "ECA PSV (cm/s)", "Vertebral PSV (cm/s)"],
    anomaliesDetected: ["ICA stenosis (>50%, >70%)", "Plaque with surface ulceration", "Near-occlusion", "Occlusion", "Retrograde vertebral flow", "IMT >1.0mm"],
    steps: [
      "Patient supine, head slightly turned away from side being scanned. Use linear probe (5–12 MHz).",
      "Begin with CCA transverse sweep from clavicle to bifurcation — survey for plaque, IMT, and diameter.",
      "Longitudinal CCA: angle ≤60° to vessel, sample Doppler at proximal, mid, and distal. Document PSV and EDV.",
      "At bifurcation: identify ICA (posterior, larger, no branches) and ECA (anterior, smaller, branches). Use temporal tap test to confirm.",
      "Longitudinal ICA: sample at origin, proximal, mid, and distal. Calculate ICA/CCA PSV ratio.",
      "Measure IMT at far wall of distal CCA, 1cm proximal to bifurcation in a plaque-free segment.",
      "Vertebral artery: probe posterolateral to CCA between transverse processes. Confirm antegrade flow. Repeat all steps contralateral side.",
    ],
  },
  {
    id: "le-venous-duplex",
    name: "Lower Extremity Venous Duplex (DVT)",
    shortName: "LE Venous Duplex",
    category: "Vascular",
    indication: "Leg swelling/pain; elevated D-dimer; cancer surveillance; DVT risk",
    views: [
      "Common femoral vein (CFV) — compression + Doppler",
      "Femoral vein — mid/distal thigh compression",
      "Popliteal vein — compression + Doppler",
      "Trifurcation (peroneal, posterior tibial, anterior tibial)",
      "GSV at saphenofemoral junction",
      "Augmentation maneuvers (calf squeeze)",
    ],
    keyFindings: ["Vein compressibility", "Intraluminal echogenic material", "Augmentation response", "Spontaneous flow pattern", "Phasicity with respiration"],
    commonPitfalls: ["Duplicate femoral veins — interrogate both", "Calf DVT limited sensitivity without Doppler augmentation", "Chronic DVT: thickened, echogenic wall ≠ acute thrombus"],
    tip: "Normal vein fully compresses (walls touch). Non-compressibility = DVT. Compare Doppler phasicity: loss = proximal obstruction.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["CFV diameter (mm)", "Popliteal vein diameter (mm)", "Compressibility score", "Flow velocity (cm/s)"],
    anomaliesDetected: ["Acute DVT (non-compressible)", "Chronic DVT (wall thickening)", "Partial thrombosis", "Absent augmentation (proximal obstruction)"],
    steps: [
      "Patient supine with leg slightly externally rotated. Use linear probe (5–12 MHz).",
      "Start at CFV in the groin: transverse view, compress fully — walls should touch. Scan proximally to SFJ.",
      "Sweep distally in transverse with compression every 1–2 cm through the femoral vein in the thigh.",
      "At the popliteal fossa (patient prone or knee bent): compress popliteal vein transversely from distal thigh to trifurcation.",
      "Add color Doppler and augmentation (calf squeeze releases): normal response is flow augmentation. Loss = proximal obstruction.",
      "Assess phasicity: normal venous flow waxes/wanes with respiration. Continuous non-phasic flow = proximal obstruction.",
      "Document each segment: compressible (normal), non-compressible (DVT), echogenic thrombus characteristics.",
    ],
    measurements: [
      {
        structure: "Common Femoral Vein (CFV) Diameter",
        landmark: "Transverse view at the groin, at the level of the saphenofemoral junction. Measure lumen diameter before compression.",
        normal: "Variable; non-compressibility is more important than diameter alone",
        technique: "Compress fully — normal vein walls fully touch (compressible = no DVT). Do not rely on diameter alone.",
      },
      {
        structure: "Popliteal Vein Diameter",
        landmark: "Posterior popliteal fossa, transverse view, with the knee slightly flexed. Inner wall to inner wall.",
        normal: "Variable; non-compressibility is diagnostic of DVT",
        technique: "Patient prone or knee flexed. Apply compression — walls should fully touch. Measure at mid-popliteal fossa.",
      },
    ],
  },
  {
    id: "dvt",
    name: "DVT: Compression Ultrasound (POCUS)",
    shortName: "DVT POCUS",
    category: "Vascular",
    indication: "Suspected DVT at bedside; leg swelling; PE workup",
    views: ["Common femoral vein (CFV)", "Femoral vein (mid-thigh)", "Popliteal vein", "Trifurcation"],
    keyFindings: ["Vein compressibility", "Intraluminal thrombus echogenicity", "Doppler flow pattern", "Augmentation"],
    commonPitfalls: ["Always compare to artery — arteries are pulsatile and don't fully compress", "Calf veins require experienced operators"],
    tip: "Normal: vein fully compresses (walls touch). DVT: vein non-compressible or partially compressible.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "5–8 min",
    aiMeasurements: ["CFV diameter (mm)", "Compressibility score"],
    anomaliesDetected: ["Non-compressible vein (DVT)", "Intraluminal echogenic material", "Absent augmentation"],
    steps: [
      "Patient supine, leg slightly externally rotated. Linear probe (5–12 MHz).",
      "Groin: identify CFV in transverse. It is medial and compressible — artery is lateral and pulsatile.",
      "Apply firm downward pressure — normal vein walls fully touch. Non-compressible = DVT.",
      "Scan femoral vein in mid-thigh with sequential compression every 2cm.",
      "Popliteal vein: flex knee or prone position. Compress transversely from above to below the knee.",
      "Add color Doppler and squeeze calf — confirm augmentation response at each level.",
      "A 2-point compression study (CFV + popliteal) has high sensitivity for proximal DVT in low-risk patients.",
    ],
  },
  {
    id: "le-arterial-duplex",
    name: "Lower Extremity Arterial Duplex",
    shortName: "LE Arterial",
    category: "Vascular",
    indication: "Leg claudication; rest pain; non-healing wounds; ABI abnormality; pre-revascularization mapping; peripheral artery disease",
    views: [
      "Aortoiliac segment — Doppler",
      "Common femoral artery (CFA) — Doppler",
      "Superficial femoral artery (SFA) — proximal, mid, distal",
      "Popliteal artery — Doppler",
      "Tibioperoneal trunk + anterior tibial artery",
      "Posterior tibial artery — Doppler",
      "Peroneal artery — Doppler",
      "Dorsalis pedis artery — Doppler",
    ],
    keyFindings: [
      "Waveform character (triphasic/biphasic/monophasic)",
      "PSV and PSV ratio at each segment",
      "Plaque burden and calcification",
      "Stenosis location and severity",
      "Collateral vessel development",
    ],
    commonPitfalls: [
      "Highly calcified vessels (Mönckeberg sclerosis) may be non-compressible — do not confuse with occlusion",
      "A PSV ratio >2.0 indicates ≥50% stenosis; >4.0 indicates >70% stenosis",
      "Monophasic waveform distally may reflect inflow disease rather than local disease",
      "Heavy calcification causes acoustic shadowing — rely on Doppler alone at those segments",
    ],
    tip: "Document ABI before the exam. An ABI <0.9 confirms PAD; <0.4 indicates critical limb ischemia. Triphasic → biphasic → monophasic waveform progression indicates increasing proximal inflow disease.",
    icon: "🦵",
    difficulty: "Intermediate",
    estimatedTime: "45–60 min",
    aiMeasurements: ["CFA PSV (cm/s)", "SFA PSV (cm/s)", "Popliteal PSV (cm/s)", "Posterior tibial PSV (cm/s)", "PSV ratio at stenosis", "ABI correlation"],
    anomaliesDetected: ["Stenosis ≥50% (PSV ratio >2.0)", "Occlusion (absent flow)", "Monophasic waveform (inflow disease)", "Aneurysm", "Pseudoaneurysm", "Calcified plaque"],
    steps: [
      "Record bilateral ankle-brachial index (ABI) before scanning. Patient supine. Use linear probe (5–12 MHz); curved probe for proximal iliacs.",
      "Begin at CFA in groin: transverse survey for plaque, then longitudinal Doppler. Note waveform character — triphasic is normal in a resting limb.",
      "Follow SFA from groin to adductor canal: scan in transverse to identify stenosis or occlusion, then sample Doppler every 5–10 cm. Calculate PSV ratio at any focal acceleration (>2.0 = ≥50% stenosis).",
      "Popliteal artery: probe posteriorly or medially with knee slightly flexed. Sample Doppler proximal, mid, and distal popliteal.",
      "Tibioperoneal trunk: identify bifurcation below popliteal fossa. Follow posterior tibial (medial) and peroneal arteries.",
      "Anterior tibial artery: begins at bifurcation, courses anterolaterally through interosseous membrane. Follow to dorsalis pedis at dorsum of foot.",
      "Document each segment as: normal triphasic, biphasic (mild-moderate disease), monophasic (severe inflow disease), or absent (occlusion). Note collateral vessels bridging occlusions.",
    ],
  },
  {
    id: "ue-arterial-duplex",
    name: "Upper Extremity Arterial Duplex",
    shortName: "UE Arterial",
    category: "Vascular",
    indication: "Arm claudication; digital ischemia; post-catheterization; dialysis access planning; thoracic outlet syndrome",
    views: [
      "Subclavian artery — Doppler",
      "Axillary artery — Doppler",
      "Brachial artery — Doppler",
      "Radial artery — Doppler",
      "Ulnar artery — Doppler",
      "Palmar arch patency",
    ],
    keyFindings: ["Waveform character (triphasic/biphasic/monophasic)", "PSV and waveform at each segment", "Pressure gradients", "Plaque or stenosis", "Thrombosis"],
    commonPitfalls: ["Systolic pressure differential >15mmHg between arms = significant asymmetry", "Triphasic → monophasic waveform transition = significant inflow disease", "Thoracic outlet requires dynamic (postural) assessment"],
    tip: "Compare bilateral brachial pressures. A >20% PSV elevation at a focal segment indicates hemodynamically significant stenosis.",
    icon: "🩸",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Brachial PSV (cm/s)", "Radial PSV (cm/s)", "Ulnar PSV (cm/s)", "Pressure index"],
    anomaliesDetected: ["Stenosis (focal PSV elevation)", "Occlusion (absent flow)", "Monophasic waveform (inflow disease)", "Pseudoaneurysm", "AV fistula"],
    steps: [
      "Patient supine, arm extended. Use linear probe (5–12 MHz). Record bilateral brachial blood pressures first.",
      "Subclavian artery: probe at supraclavicular fossa. Sample Doppler — note waveform character (triphasic = normal).",
      "Axillary → brachial artery: follow artery distally with Doppler at regular intervals. Maintain angle ≤60°.",
      "At antecubital fossa, identify brachial bifurcation into radial (lateral) and ulnar (medial) arteries.",
      "Follow radial and ulnar arteries to wrist. Document PSV and waveform at each level.",
      "Note any transition from triphasic to biphasic to monophasic — indicates progressive proximal disease.",
      "Repeat on contralateral arm. A PSV increase of >100% at a focal site = hemodynamically significant stenosis.",
    ],
  },
  {
    id: "ue-venous-duplex",
    name: "Upper Extremity Venous Duplex (DVT)",
    shortName: "UE Venous",
    category: "Vascular",
    indication: "Arm/hand swelling; PICC/catheter-related thrombosis; effort thrombosis (Paget-Schroetter); cancer surveillance",
    views: [
      "Internal jugular vein — compression + Doppler",
      "Subclavian vein — Doppler",
      "Axillary vein — compression + Doppler",
      "Brachial veins — compression",
      "Cephalic and basilic veins",
    ],
    keyFindings: ["Vein compressibility", "Intraluminal thrombus", "Doppler phasicity", "Augmentation with arm compression", "PICC/catheter position"],
    commonPitfalls: ["Subclavian vein not compressible due to clavicle — rely on Doppler only", "IJV thrombosis may be incidental finding", "Respiratory phasicity loss indicates central (SVC) obstruction"],
    tip: "Respiratory variation in the subclavian/axillary Doppler signal indicates patency to central veins. Loss of variation = central obstruction.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "20–30 min",
    aiMeasurements: ["IJV diameter (mm)", "Subclavian vein flow (cm/s)", "Compressibility score"],
    anomaliesDetected: ["Acute DVT (non-compressible)", "PICC-associated thrombosis", "Effort thrombosis (subclavian)", "SVC syndrome signs"],
    steps: [
      "Patient supine, head turned slightly away. Linear probe (5–12 MHz).",
      "IJV: probe lateral to carotid at the neck. Compress in transverse — IJV collapses easily (artery does not).",
      "Subclavian vein: probe in infraclavicular region. Cannot fully compress due to clavicle — rely on Doppler phasicity.",
      "Axillary vein: arm slightly abducted. Compress transversely from axilla to upper arm.",
      "Brachial, basilic, and cephalic veins: linear compression sweeps from axilla to antecubital fossa.",
      "Add color Doppler at subclavian: confirm respiratory phasicity. Loss of variation = central (SVC) obstruction.",
      "If PICC present: trace catheter track and assess for surrounding thrombus along its course.",
    ],
  },
  {
    id: "renal-artery-duplex",
    name: "Renal Artery Duplex Ultrasound",
    shortName: "Renal Artery",
    category: "Vascular",
    indication: "Resistant hypertension; renovascular disease; renal artery stenosis screening; transplant surveillance",
    views: [
      "Aorta at renal artery origins — transverse",
      "Right renal artery — origin + mid segment Doppler",
      "Left renal artery — origin + mid segment Doppler",
      "Right renal parenchyma — segmental/interlobar arteries",
      "Left renal parenchyma — segmental/interlobar arteries",
      "Kidney lengths — bilateral",
    ],
    keyFindings: ["Renal artery PSV at origin", "Renal/aortic ratio (RAR)", "Resistive index (RI) parenchymal", "Kidney size asymmetry", "Post-stenotic turbulence"],
    commonPitfalls: ["Bowel gas is the major limiting factor — patient prep essential", "Accessory renal arteries in 20–30% of patients", "RAR >3.5 indicates significant stenosis", "Long exam — patient positioning is crucial"],
    tip: "PSV >180 cm/s at renal artery origin + RAR >3.5 = significant stenosis. RI >0.8 = poor response to revascularization.",
    icon: "🩸",
    difficulty: "Advanced",
    estimatedTime: "45–75 min",
    aiMeasurements: ["Renal artery PSV (cm/s)", "Aortic PSV (cm/s)", "RAR (renal/aortic ratio)", "RI (resistive index)", "Kidney length (cm)"],
    anomaliesDetected: ["Renal artery stenosis (RAR >3.5)", "Fibromuscular dysplasia", "Kidney size asymmetry (>2cm)", "Elevated RI (parenchymal disease)"],
    steps: [
      "Patient fasting 6–8 hours to minimise bowel gas. Supine or slight oblique. Curvilinear probe.",
      "Aorta: transverse view at the level of renal arteries (L1–L2). Sample aortic PSV for RAR calculation.",
      "Right renal artery: from aorta, angle probe right. Follow RA origin to hilum. Sample at origin, proximal, and mid-segment.",
      "Left renal artery: rotate/angle left from aorta. Follow posterior and lateral course to left kidney.",
      "Both kidneys: measure length longitudinally. Asymmetry >2cm suggests renovascular disease on smaller side.",
      "Parenchymal Doppler: sample segmental/interlobar arteries in upper, mid, and lower poles. Calculate RI = (PSV−EDV)/PSV.",
      "RAR (renal artery PSV / aortic PSV) >3.5 = significant stenosis. RI >0.80 = poor revascularization prognosis.",
    ],
  },
  {
    id: "abi",
    name: "ABI & Physiologic Segmental Pressures",
    shortName: "ABI",
    category: "Vascular",
    indication: "Peripheral arterial disease assessment; claudication; non-healing wounds; ischemia risk stratification",
    views: [
      "Bilateral brachial pressures (baseline)",
      "High thigh cuff pressure",
      "Above-knee (AK) cuff pressure",
      "Below-knee (BK) cuff pressure",
      "Ankle pressures (DP + PT bilateral)",
      "Toe pressures (TBI) if indicated",
    ],
    keyFindings: ["ABI calculation (ankle ÷ brachial)", "Segmental pressure gradients", "Waveform character at each level", "TBI for calcified vessels"],
    commonPitfalls: ["Calcified vessels (diabetics, ESRD): ABI >1.4 is non-compressible — use TBI instead", "ABI 0.91–1.0 = borderline; 0.71–0.90 = mild PAD; 0.41–0.70 = moderate; ≤0.40 = severe", "Exercise ABI adds sensitivity when resting ABI is normal"],
    tip: "Always take the higher of DP and PT for the ankle pressure. ABI ≤0.9 is diagnostic of PAD. ABI >1.4 = incompressible — order TBI.",
    icon: "📊",
    difficulty: "Basic",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Right ABI", "Left ABI", "Segmental pressures (mmHg)", "TBI"],
    anomaliesDetected: ["ABI ≤0.9 (PAD)", "ABI >1.4 (calcified, non-compressible)", "Segmental gradient >20mmHg", "Critical limb ischemia (ABI <0.4)"],
    steps: [
      "Patient supine, 10 min rest. Place appropriate cuffs: bilateral brachial, high thigh, above-knee, below-knee, ankle.",
      "Bilateral brachial pressures: use handheld Doppler over brachial artery. Record the higher value as reference.",
      "Segmental pressures: inflate each cuff to suprasystolic, then slowly deflate. Use Doppler over DP or PT to detect return of signal.",
      "Ankle pressures: DP and PT on each side. Use the higher ankle value for ABI calculation.",
      "ABI = highest ankle pressure ÷ highest brachial pressure. Normal ≥0.9; PAD ≤0.9; Critical ischemia <0.4.",
      "If ABI >1.4 (incompressible): measure toe pressures using photoplethysmography (PPG). TBI <0.6 = PAD.",
      "Document waveforms at each level: triphasic = normal, biphasic = mild disease, monophasic = significant disease.",
    ],
  },
  {
    id: "aaa",
    name: "Abdominal Aorta (AAA Screening)",
    shortName: "AAA",
    category: "Vascular",
    indication: "AAA screening; flank/back pain in elderly; syncope with pain",
    views: ["Proximal aorta (subxiphoid transverse)", "Mid aorta (transverse)", "Distal aorta to bifurcation", "Longitudinal aorta"],
    keyFindings: ["Aortic diameter (AP + transverse)", "Intraluminal thrombus", "Periaortic hematoma", "Iliac vessels"],
    commonPitfalls: ["Measure outer wall to outer wall", "Bowel gas obscuring view — gentle pressure or reposition", "Don't confuse IVC for aorta"],
    tip: "Aorta is pulsatile and LEFT of midline; IVC is compressible and RIGHT of midline.",
    icon: "🩸",
    difficulty: "Basic",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Max AP diameter (cm)", "Transverse diameter (cm)"],
    anomaliesDetected: ["Dilation >3cm (aneurysm threshold)", "Dilation >5.5cm (surgical threshold)", "Intraluminal thrombus", "Periaortic fluid"],
    steps: [
      "Patient supine. Use curvilinear probe. Start at the epigastrium just below xiphoid.",
      "Transverse view: identify aorta (left of midline, pulsatile, non-compressible). IVC is to the right and compressible.",
      "Sweep distally from diaphragm to bifurcation (at level of umbilicus, ~L4). Measure AP diameter in transverse at widest point.",
      "Measure outer-wall to outer-wall — this is the standard for AAA sizing.",
      "Longitudinal view: confirm diameter and assess for mural thrombus (echogenic crescent lining vessel wall).",
      "Look for periaortic hematoma (hypoechoic shadowing around aorta) — in the right clinical context this suggests rupture.",
      "Measure iliac arteries bilaterally if aorta is dilated. Normal iliac <1.5cm.",
    ],
    measurements: [
      {
        structure: "Abdominal Aortic Diameter",
        landmark: "Widest transverse outer-wall-to-outer-wall diameter. Measure at the level of maximum dilation — typically at or just below the renal arteries.",
        normal: "< 3 cm = normal; 3.0–5.4 cm = AAA (monitor); ≥ 5.5 cm = surgical threshold (men); ≥ 5.0 cm = surgical threshold (women)",
        technique: "ALWAYS measure in TRANSVERSE — sagittal views underestimate true diameter. Measure outer edge to outer edge (including walls). Check at the celiac axis, SMA origin, and just above bifurcation.",
      },
      {
        structure: "Iliac Artery Diameter",
        landmark: "Common iliac arteries bilaterally, transverse view, outer wall to outer wall at the widest point.",
        normal: "< 1.5 cm; ≥ 1.5 cm = iliac aneurysm",
        technique: "Trace the aorta to its bifurcation (level of umbilicus, ~L4). Evaluate both common iliac arteries. Iliac aneurysms often coexist with AAA.",
      },
    ],
  },
  {
    id: "vein-mapping",
    name: "Vein Mapping (Pre-Access / CABG)",
    shortName: "Vein Mapping",
    category: "Vascular",
    indication: "Pre-operative saphenous vein conduit planning for CABG; dialysis access planning; PICC line mapping",
    views: [
      "GSV at SFJ — diameter + compressibility",
      "GSV thigh segment — diameter every 10cm",
      "GSV knee — diameter",
      "GSV lower leg — diameter",
      "Small saphenous vein (SSV)",
      "Cephalic vein — UE (diameter every 10cm)",
      "Basilic vein — UE (diameter every 10cm)",
    ],
    keyFindings: ["Vein diameter at each segment", "Compressibility (no DVT)", "Vein depth from skin", "Continuity (no segments)", "Varicosities"],
    commonPitfalls: ["Tourniquet application improves vein distension for mapping", "Measure in standing position for lower extremity — supine underestimates diameter", "Deep veins must be assessed for DVT before harvest"],
    tip: "Vein diameter ≥3mm is considered adequate for CABG conduit. Diameter ≥2.5mm at wrist is adequate for dialysis fistula creation.",
    icon: "🗺️",
    difficulty: "Intermediate",
    estimatedTime: "30–60 min",
    aiMeasurements: ["GSV diameter per segment (mm)", "Cephalic vein diameter (mm)", "Basilic vein diameter (mm)", "Depth from skin (cm)"],
    anomaliesDetected: ["Inadequate diameter (<3mm)", "Thrombosed segment", "Varicose segment", "Deep accessory system dependence"],
    steps: [
      "Patient standing for lower extremity mapping (supine underestimates vein diameter). Apply tourniquet above scan level.",
      "GSV mapping: start at SFJ (groin), confirm competence, measure diameter. Mark every 10cm distally to ankle.",
      "At each mark: record GSV diameter, depth from skin, continuity, and note any varicosities or thrombosed segments.",
      "SSV: probe popliteal fossa — identify at SPJ. Map to mid-calf.",
      "Upper extremity (supine): cephalic vein from wrist to shoulder. Basilic from antecubital to axilla. Measure every 10cm.",
      "Confirm all veins are compressible and free of thrombus before marking as usable conduit.",
      "Mark skin with indelible marker. Minimum 3mm diameter for CABG; 2.5mm at wrist for dialysis fistula.",
    ],
  },
  {
    id: "avf-surveillance",
    name: "AV Fistula / Graft Surveillance",
    shortName: "AVF Surveillance",
    category: "Vascular",
    indication: "Dialysis access monitoring; maturation assessment; dysfunction evaluation (poor flow, clotting, difficult cannulation)",
    views: [
      "Arterial anastomosis — Doppler",
      "Venous outflow — Doppler sweep",
      "Mid-access — Doppler",
      "Juxta-anastomotic vein segment",
      "Outflow vein to central veins",
      "Brachial artery inflow — Doppler + volume flow",
    ],
    keyFindings: ["Brachial artery volume flow (mL/min)", "PSV at anastomosis and outflow", "Stenosis PSV ratio", "Access vein diameter and depth", "Thrombus"],
    commonPitfalls: ["Volume flow <500 mL/min predicts access failure", "PSV ratio >2:1 at stenosis = hemodynamically significant", "Aneurysms common — measure largest diameter", "Central stenosis presents as diffuse arm swelling + high pressures"],
    tip: "Volume flow calculation: π × r² × TAMEAN × 60. A flow >600 mL/min indicates maturation. Surveillance every 3–6 months reduces thrombosis risk.",
    icon: "🔄",
    difficulty: "Intermediate",
    estimatedTime: "20–30 min",
    aiMeasurements: ["Brachial artery volume flow (mL/min)", "Access vein diameter (mm)", "Stenosis PSV ratio", "Anastomosis PSV (cm/s)"],
    anomaliesDetected: ["Stenosis (PSV ratio >2:1)", "Thrombosis", "Pseudoaneurysm", "Low flow (<500 mL/min)", "Steal syndrome signs"],
    steps: [
      "Patient supine, arm extended. Linear probe (5–12 MHz). Palpate access for thrill before scanning.",
      "Begin at the arterial anastomosis: document PSV and waveform. Turbulence here is normal.",
      "Sweep along the juxta-anastomotic vein (most common stenosis site). Flag any focal PSV elevation.",
      "Continue sweep along the access vein to the outflow — document PSV at regular intervals and at any stenosis.",
      "Volume flow: measure brachial artery PSV and diameter. Volume flow = π × r² × TAMEAN × 60. Normal mature fistula >600 mL/min.",
      "Assess aneurysmal segments: measure largest diameter. Note pseudoaneurysms (pulsatile sac with yin-yang flow).",
      "Check for steal: Doppler at radial artery distal to anastomosis — retrograde flow = steal syndrome.",
    ],
  },
  {
    id: "venous-reflux",
    name: "Lower Extremity Venous Reflux Study",
    shortName: "Venous Reflux",
    category: "Vascular",
    indication: "Varicose veins; chronic venous insufficiency; post-thrombotic syndrome; pre-ablation mapping",
    views: [
      "SFJ — reflux with Valsalva/cuff release",
      "GSV thigh — reflux assessment",
      "GSV below knee — reflux",
      "SSV at SPJ — reflux with calf compression",
      "Deep system — CFV, FV, popliteal vein reflux",
      "Perforating veins — bidirectional flow",
    ],
    keyFindings: ["Reflux duration at SFJ and GSV (>0.5s = pathologic)", "Perforating vein reflux (>0.35s bidirectional flow)", "GSV diameter in standing position", "SPJ competence", "Deep vein reflux"],
    commonPitfalls: ["Study must be performed in standing or reverse Trendelenburg position — supine gives false negatives", "Reflux >0.5s in superficial veins is pathologic; >1s in deep veins is pathologic", "Augmentation should be distal-to-proximal (cuff inflation then release)"],
    tip: "Perform in standing position. Augment distally and release to provoke reflux. Mark GSV with skin marker for ablation planning.",
    icon: "🔁",
    difficulty: "Intermediate",
    estimatedTime: "45–60 min (bilateral)",
    aiMeasurements: ["Reflux duration (seconds)", "GSV diameter standing (mm)", "Perforator diameter (mm)"],
    anomaliesDetected: ["GSV reflux (>0.5s)", "SSV reflux", "Perforator incompetence", "SFJ incompetence", "Post-thrombotic changes"],
    steps: [
      "Patient standing or in reverse Trendelenburg. Supine gives false negatives — this step is mandatory.",
      "SFJ: probe at groin, GSV origin. Apply distal cuff augmentation then release — time any retrograde flow. >0.5s = pathologic reflux.",
      "GSV thigh: follow GSV distally, augmenting and releasing at each level. Mark refluxing segments.",
      "GSV below knee: continue to ankle if reflux present. Measure GSV diameter in standing.",
      "SPJ/SSV: probe popliteal fossa. Identify SSV entering popliteal vein. Augment calf and release — assess for reflux.",
      "Perforating veins: thick-walled veins connecting superficial to deep. Bidirectional flow >0.35s = incompetent.",
      "Deep system: assess CFV, FV, and popliteal for reflux (>1.0s in deep veins is pathologic). Mark all incompetent segments for ablation planning.",
    ],
  },

  // ── THYROID ──────────────────────────────────────────────────────────────────
  {
    id: "thyroid",
    name: "Thyroid Ultrasound",
    shortName: "Thyroid US",
    category: "Thyroid",
    indication: "Palpable thyroid nodule; elevated TSH/T4; goiter evaluation; nodule surveillance; pre-biopsy planning",
    views: [
      "Right lobe — transverse sweep (superior to inferior)",
      "Right lobe — longitudinal (length measurement)",
      "Isthmus — transverse (AP diameter)",
      "Left lobe — transverse sweep",
      "Left lobe — longitudinal",
      "Nodule(s) — 3 planes with measurements",
      "Vascularity — color/power Doppler",
      "Lymph nodes — bilateral central and lateral",
    ],
    keyFindings: ["Lobe dimensions and volume", "Isthmus thickness", "Nodule size, echogenicity, composition", "Nodule margins and orientation", "Echogenic foci (microcalcifications, comet-tail)", "Lymph node morphology"],
    commonPitfalls: ["TI-RADS scoring requires correct classification of composition (cystic >50% drops score)", "Comet-tail artifacts = benign colloid; microcalcifications = high-risk feature", "Posterior shadowing from calcification obscures deeper nodule assessment"],
    tip: "Use ACR TI-RADS: score each nodule for composition, echogenicity, shape, margin, echogenic foci. TR1/TR2 = no FNA; TR3 ≥1.5cm; TR4 ≥1.0cm; TR5 ≥0.5cm.",
    icon: "🫁",
    difficulty: "Basic",
    estimatedTime: "20–30 min",
    aiMeasurements: ["Right lobe volume (mL)", "Left lobe volume (mL)", "Isthmus AP (mm)", "Nodule dimensions (mm)", "ACR TI-RADS score"],
    anomaliesDetected: ["Thyroid nodule (solid/cystic/mixed)", "Microcalcifications (high suspicion)", "Irregular margins", "Taller-than-wide shape", "Goiter", "Lymphadenopathy", "Hashimoto pattern"],
    steps: [
      "Patient supine with neck slightly extended (pillow under shoulders). High-frequency linear probe (10–18 MHz).",
      "Transverse sweep: start at the right lobe superior pole, sweep inferiorly to isthmus. Repeat for left lobe.",
      "Measure right lobe in transverse (width + AP) at the largest dimension, and longitudinally (length).",
      "Measure isthmus AP in transverse. Measure left lobe in same planes.",
      "For each nodule: document location, size (3 planes), composition (cystic/solid/mixed), echogenicity, shape, margins, and echogenic foci.",
      "Apply ACR TI-RADS scoring: assign points for each feature. Total determines FNA threshold.",
      "Color Doppler: note vascularity pattern (peripheral, internal, or absent). Survey central and lateral neck nodes.",
    ],
  },

  // ── NEURO ────────────────────────────────────────────────────────────────────
  {
    id: "onsd",
    name: "Optic Nerve Sheath Diameter (ICP)",
    shortName: "ONSD",
    category: "Neuro",
    indication: "Suspected raised ICP; TBI; headache with neuro signs; pre-LP assessment",
    views: ["Transverse ONSD (3mm posterior to globe)", "Longitudinal ONSD"],
    keyFindings: ["ONSD measurement", "Globe architecture", "Posterior globe flattening (severe ICP)"],
    commonPitfalls: ["Measure exactly 3mm behind globe posterior wall", "Use light pressure only — globe is fragile"],
    tip: "ONSD >5.0–5.7mm (varies by study) correlates with ICP >20 mmHg. Use linear probe with standoff gel pad.",
    icon: "👁️",
    difficulty: "Basic",
    estimatedTime: "3–4 min",
    aiMeasurements: ["ONSD bilateral (mm)", "Globe axial length (mm)"],
    anomaliesDetected: ["Elevated ONSD (>5.7mm)", "Posterior globe flattening", "Papilledema signs"],
    steps: [
      "Patient supine with eyes closed. Use linear probe (7–15 MHz) with a generous standoff gel pad — do NOT apply pressure to the globe.",
      "Place gel pad on closed eyelid. Orient probe transversely over the eye.",
      "Identify the globe (anechoic sphere), lens (anterior hyperechoic arc), and optic nerve (hypoechoic tract exiting posteriorly).",
      "Measure ONSD exactly 3mm posterior to the posterior wall of the globe, perpendicular to the nerve.",
      "Normal ONSD ≤5.0–5.7mm (varies by reference). >5.7mm correlates with ICP >20 mmHg.",
      "Rotate probe 90° for the longitudinal plane — repeat measurement. Average transverse and longitudinal.",
      "Repeat on the contralateral eye. Bilateral elevation strengthens the correlation with raised ICP.",
    ],
  },
  {
    id: "tcd",
    name: "Transcranial Doppler (TCD)",
    shortName: "TCD",
    category: "Neuro",
    indication: "Stroke risk in sickle cell disease; cerebral vasospasm (post-SAH); intracranial stenosis; right-to-left shunt detection; brain death confirmation",
    views: [
      "Transtemporal window — MCA (45–65mm)",
      "Transtemporal window — ACA (60–80mm)",
      "Transtemporal window — PCA (60–70mm)",
      "Transorbital window — ophthalmic artery (REDUCE POWER)",
      "Suboccipital window — basilar artery (80–120mm)",
      "Suboccipital window — vertebral arteries (40–70mm)",
    ],
    keyFindings: ["MCA PSV (normal: 50–120 cm/s)", "Lindegaard Ratio (vasospasm)", "Vertebral/basilar flow direction", "Microembolic signals (HITS)", "Ophthalmic artery flow direction"],
    commonPitfalls: ["Temporal window absent in 10–20% of patients (elderly women, thick skull)", "REDUCE power to minimum MI for transorbital window — retinal risk", "MCA flows TOWARD probe (positive); ACA flows AWAY (negative)"],
    tip: "Vasospasm: MCA PSV >120 cm/s + Lindegaard Ratio >3. For PFO detection, inject agitated saline during Valsalva and count HITS within 25 cardiac cycles.",
    icon: "🧠",
    difficulty: "Advanced",
    estimatedTime: "45–60 min",
    aiMeasurements: ["MCA PSV (cm/s)", "ACA PSV (cm/s)", "PCA PSV (cm/s)", "Basilar PSV (cm/s)", "Lindegaard Ratio"],
    anomaliesDetected: ["MCA PSV >120 cm/s (vasospasm/sickle cell risk)", "Reversed ophthalmic flow (ICA occlusion)", "Absent flow (brain death criteria)", "HITS (microemboli)", "Lindegaard Ratio >3"],
    steps: [
      "Patient supine. Use sector/phased array probe (2 MHz TCD probe preferred) set to low MI.",
      "Transtemporal window: place probe at the temporal squama above the zygomatic arch. Identify the MCA at 45–65mm depth — it flows toward the probe (positive).",
      "Identify ACA at 60–80mm (flows away, negative). PCA at 60–70mm (flow direction varies by segment).",
      "Record PSV, EDV, and mean velocity at each vessel. Calculate Lindegaard Ratio = MCA mean / ICA mean (>3 = vasospasm).",
      "Transorbital window: REDUCE power to minimum MI. Place probe on closed eyelid. Ophthalmic artery at 40–50mm — normally toward probe.",
      "Suboccipital window: patient flexes neck. Probe at foramen magnum. Basilar at 80–120mm (away from probe); vertebrals at 40–70mm.",
      "For PFO: inject agitated saline IV during Valsalva. Count HITS (microembolic signals) within 25 cardiac cycles on MCA.",
    ],
  },

  // ── MSK ──────────────────────────────────────────────────────────────────────
  {
    id: "shoulder",
    name: "Shoulder Ultrasound (Rotator Cuff)",
    shortName: "Shoulder US",
    category: "MSK",
    indication: "Rotator cuff tear; impingement syndrome; shoulder pain; biceps tendon pathology; AC joint assessment",
    views: [
      "Biceps tendon — transverse (long axis groove)",
      "Biceps tendon — longitudinal",
      "Subscapularis tendon — transverse + longitudinal",
      "Supraspinatus tendon — long axis (modified Crass)",
      "Supraspinatus tendon — short axis",
      "Infraspinatus tendon — long + short axis",
      "AC joint — transverse",
      "Subacromial-subdeltoid bursa",
      "Dynamic impingement (arm elevation)",
    ],
    keyFindings: ["Supraspinatus continuity and echogenicity", "Bursal and articular surface tears", "Tendon thickness", "Biceps tendon integrity and position", "Subdeltoid bursal fluid", "Calcific deposits"],
    commonPitfalls: ["Anisotropy artifact mimics tears — always scan perpendicular to tendon fibers", "Tendon thickness must be compared to contralateral side", "Full-thickness tears: absent tendon, 'naked tuberosity' sign", "Patient must be in standard position (modified Crass for supraspinatus)"],
    tip: "Modified Crass position: arm internally rotated, hand on ipsilateral back pocket. This stretches supraspinatus for best visualization. Dynamic assessment during arm elevation can provoke impingement.",
    icon: "🦴",
    difficulty: "Intermediate",
    estimatedTime: "20–30 min",
    aiMeasurements: ["Supraspinatus thickness (mm)", "Bursal fluid depth (mm)", "Tear size if present (mm)", "Biceps tendon diameter (mm)"],
    anomaliesDetected: ["Full-thickness rotator cuff tear", "Partial-thickness tear (bursal/articular)", "Tendinosis", "Calcific tendinopathy", "Biceps tendon rupture/dislocation", "Subdeltoid bursitis"],
    steps: [
      "Patient seated on a stool facing you. Use high-frequency linear probe (10–18 MHz) with plenty of gel.",
      "Biceps tendon: arm in neutral, elbow flexed 90°. Probe transverse in the bicipital groove — identify as round echogenic structure. Rotate longitudinal to assess continuity.",
      "Subscapularis: internally rotate arm (palm up on thigh). Transverse then longitudinal scan of the subscapularis tendon.",
      "Supraspinatus — modified Crass position: patient places hand in back pocket (internally rotated). Probe coronal on the anterior shoulder. Long axis first, then short axis.",
      "Infraspinatus: arm in neutral, probe at posterior shoulder lateral to spine of scapula. Long and short axis.",
      "Subacromial-subdeltoid bursa: thin anechoic line between cuff and deltoid. Any fluid >2mm = bursitis.",
      "Dynamic assessment: slowly abduct the arm while scanning — observe for impingement of cuff against acromion.",
    ],
  },

  // ── PROCEDURAL ───────────────────────────────────────────────────────────────
  {
    id: "soft-tissue",
    name: "Soft Tissue / Abscess",
    shortName: "Soft Tissue",
    category: "Procedural",
    indication: "Skin and soft tissue infection; rule out abscess vs. cellulitis; foreign body",
    views: ["Affected region (transverse)", "Affected region (longitudinal)", "Surrounding tissue"],
    keyFindings: ["Fluid collection", "Internal echoes/debris", "Wall characteristics", "Vascularity (Doppler)", "Foreign body shadowing"],
    commonPitfalls: ["Cobblestone appearance = cellulitis (no drainable collection)", "Hypoechoic ≠ always abscess — compare to other side"],
    tip: "Squish sign: gentle compression causes swirling internal debris = abscess. Absence = solid mass or hematoma.",
    icon: "🔬",
    difficulty: "Intermediate",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Collection dimensions (cm)", "Depth from skin (cm)"],
    anomaliesDetected: ["Abscess (fluid + debris)", "Cellulitis (cobblestone)", "Foreign body", "Hematoma"],
    steps: [
      "Use high-frequency linear probe (10–18 MHz). No special patient preparation needed.",
      "Survey the affected area in two perpendicular planes. Compare to the contralateral side when possible.",
      "Cellulitis pattern: diffuse hyperechogenicity of subcutaneous fat with cobblestone appearance (edematous fat lobules separated by fluid).",
      "Abscess: look for a hypoechoic/anechoic collection. Apply the squish sign — gentle compression causes internal swirling of debris = abscess.",
      "If collection found: measure in 3 planes. Note depth from skin, wall characteristics, internal echoes, and vascularity with color Doppler.",
      "Foreign body: linear hyperechoic structure with posterior shadowing (wood) or reverberation artifact (metal/glass).",
      "Document all findings. For abscess drainage guidance: confirm needle trajectory in real time.",
    ],
  },
];

export const CATEGORIES: Category[] = [
  "Trauma",
  "Cardiac",
  "Lung",
  "OB/GYN",
  "Abdominal",
  "Vascular",
  "Neuro",
  "Thyroid",
  "MSK",
  "Procedural",
];

export const CATEGORY_PILL: Record<Category, { bg: string; text: string; dot: string }> = {
  Trauma:     { bg: "#fee2e2", text: "#dc2626", dot: "#ef4444" },
  Cardiac:    { bg: "#fce7f3", text: "#db2777", dot: "#ec4899" },
  Lung:       { bg: "#e0f2fe", text: "#0284c7", dot: "#38bdf8" },
  "OB/GYN":  { bg: "#f3e8ff", text: "#9333ea", dot: "#a855f7" },
  Abdominal:  { bg: "#fef9c3", text: "#a16207", dot: "#fbbf24" },
  Vascular:   { bg: "#dbeafe", text: "#2563eb", dot: "#60a5fa" },
  Neuro:      { bg: "#d1fae5", text: "#059669", dot: "#34d399" },
  Thyroid:    { bg: "#ccfbf1", text: "#0d9488", dot: "#2dd4bf" },
  MSK:        { bg: "#fef3c7", text: "#d97706", dot: "#f59e0b" },
  Procedural: { bg: "#f1f5f9", text: "#64748b", dot: "#94a3b8" },
};

// Kept for backwards-compat in any component still referencing these
export const CATEGORY_COLORS = CATEGORY_PILL;
export const CATEGORY_DOT: Record<Category, string> = Object.fromEntries(
  Object.entries(CATEGORY_PILL).map(([k, v]) => [k, v.dot])
) as Record<Category, string>;

export function getProtocolById(id: string): Protocol | undefined {
  return PROTOCOLS.find((p) => p.id === id);
}
